# Site settings
url: https://bright-softwares.com
#baseurl: /
logo-light: img/logos/large/brightsoftwares-light.png
logo-dark: img/logos/large/brightsoftwares-dark.png
logo: 'img/logos/large/brightsoftwares-light.png'
favicon: 'assets/favicon/favicon.ico'
name: Bright Softwares
short_name: "bs"

language: "en"
lang_direction: "ltr"
color: "#025159"

title: Bright Softwares
email: full@bright-softwares.com
description: "We provide solutions to our customers challenges. Our teams based in Paris and Lomé provide high value expertise to engineer the best solutions."
include: ["_pages", ".well-known"]
newsletter-url: "https://script.google.com/macros/s/AKfycbzoZaSJeefov3apqLqvLmVffsRKDkCt9NQSI9QNlfWtbs4kvdo/exec"

# Authors
authors:
  full:
    name: Full
    display_name: Full Bright
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: full3right@gmail.com
    web: https://www.bright-softwares.com
    twitter: https://twitter.com/brightsoftwares
    description: "A professional and sympathic business man."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minimagick
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

collections:
  articles:
    output: true
    permalink: /articles/:path
  
  services:
    output: true

  posts:
    permalink: /blog/:categories/:slug

# Team names, titles and social links
people:
- name: Full Bright
  pic: 1
  position: AI solutions designer
  description: Velit aut quia fugit et et. Dolorum ea voluptate vel tempore tenetur ipsa quae aut. Ipsum exercitationem iure minima enim corporis et voluptate.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Kekeli Afanou
  pic: 2
  position: Cloud Nerd
  description: Velit aut quia fugit et et. Dolorum ea voluptate vel tempore tenetur ipsa quae aut. Ipsum exercitationem iure minima enim corporis et voluptate.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Christoli Wonegou
  pic: 3
  position: Lead Developer
  description: Velit aut quia fugit et et. Dolorum ea voluptate vel tempore tenetur ipsa quae aut. Ipsum exercitationem iure minima enim corporis et voluptate.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Isa Bryant
  pic: isa2
  position: Marketing & Communication
  description: Velit aut quia fugit et et. Dolorum ea voluptate vel tempore tenetur ipsa quae aut. Ipsum exercitationem iure minima enim corporis et voluptate.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/brightsoftwares
  - title: facebook
    url: http://fb.me/bright-softwares
  - title: stack-overflow
    url: #
  - title: github
    url: http://github.com/brightsoftwares

# Postal address (add as many lines as necessary)
address:
  - line: Quartier Attiegou, Togo 200
  - line: Lomé, Togo


# Google Analytics
google_analytics: 'UA-134921119-1'

# Build settings
markdown: kramdown
permalink: pretty
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
