# Site settings
url: https://bright-softwares.com
#baseurl: /
logo-light: img/logos/large/brightsoftwares-light.png
logo-dark: img/logos/large/brightsoftwares-dark.png
logo: "img/logos/large/brightsoftwares-light.png"
favicon: "assets/favicon/favicon.ico"
name: Bright Softwares
short_name: "bs"

language: "en"
lang_direction: "ltr"
color: "#025159"

title: Bright Softwares
email: full@bright-softwares.com
description: "We provide solutions to our customers challenges. Our teams based in Paris and Lomé provide high value expertise to engineer the best solutions."
include: ["_pages", ".well-known"]
newsletter-url: "https://script.google.com/macros/s/AKfycbzoZaSJeefov3apqLqvLmVffsRKDkCt9NQSI9QNlfWtbs4kvdo/exec"

# Authors
authors:
  full:
    name: Full
    display_name: Full Bright
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: full3right@gmail.com
    web: https://www.bright-softwares.com
    twitter: https://twitter.com/brightsoftwares
    facebook: https://facebook.com/#
    instagram: https://instagram.com/#
    description: "A professional and sympathic business man."
  john:
    name: John
    display_name: John
    avatar: "assets/images/avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    facebook: https://facebook.com/#
    instagram: https://instagram.com/#
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minimagick
  - jekyll-responsive-image

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
# paginate: 6
# paginate_path: /page:num/

collections:
  articles:
    output: true
    permalink: /articles/:path

  services:
    output: true
    permalink: /:collection/:title

  posts:
    permalink: /blog/:categories/:slug
    sidebar_label: Blog posts

# Team names, titles and social links
people:
  - name: Full Bright
    pic: 1
    position: AI solutions designer
    description: An Artificial Intelligence freak. He is always building new models. We expect his solutions will solve your issues.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Kekeli Afanou
    pic: 2
    position: Cloud Nerd
    description: He is our automation nerd. He knows everything about connecting the dots to make automation your best ally.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Christoli Wonegou
    pic: 3
    position: Lead Developer
    description: Our development nerd. He is our keyboard guru.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

  - name: Isa Bryant
    pic: isa2
    position: Marketing & Communication
    description: She is our last recruit in the team. She scouts for marketing and com'.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/brightsoftwares
  - title: facebook
    url: http://fb.me/bright-softwares
  - title: stack-overflow
    url: #
  - title: github
    url: http://github.com/brightsoftwares
  - title: instagram
    url: #
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Quartier Attiegou, Togo 200
  - line: Lomé, Togo

# Google Analytics
google_analytics: "UA-134921119-1"

# Generated images
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html #THIS ONE
# [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90
# [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 856
    - width: 1400
      quality: 90
# [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false
# [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: true
# [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets
# [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}
# [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false
# [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false
# [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/*/*/*/*.{jpeg,jpg}
    - assets/*/*/*.{jpeg,jpg,png}

jekyll_admin:
  hidden_links:
  homepage: "pages"


# Build settings
markdown: kramdown
permalink: pretty
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
